<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-T4M2UU3N" name="com.orangeHRM.TestClass.loginTest" tests="7" failures="1" timestamp="2022-04-15T23:21:12 IST" time="6.273" errors="0">
  <testcase name="visibleUsertab" time="0.182" classname="com.orangeHRM.TestClass.loginTest"/>
  <system-out/>
  <testcase name="visiblepasswordtab" time="0.051" classname="com.orangeHRM.TestClass.loginTest"/>
  <system-out/>
  <testcase name="visibleLoginTab" time="0.048" classname="com.orangeHRM.TestClass.loginTest"/>
  <system-out/>
  <testcase name="visibleForgotTab" time="0.048" classname="com.orangeHRM.TestClass.loginTest"/>
  <system-out/>
  <testcase name="visibleOrangHRMTab" time="0.056" classname="com.orangeHRM.TestClass.loginTest"/>
  <system-out/>
  <testcase name="forgotpassClickabl" time="1.092" classname="com.orangeHRM.TestClass.loginTest"/>
  <system-out/>
  <testcase name="logiFunctionality" time="4.796" classname="com.orangeHRM.TestClass.loginTest">
    <failure type="java.lang.AssertionError" message="expected [://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/dashboard]">
      <![CDATA[java.lang.AssertionError: expected [://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/dashboard]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.orangeHRM.TestClass.loginTest.logiFunctionality(loginTest.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logiFunctionality -->
  <system-out/>
</testsuite> <!-- com.orangeHRM.TestClass.loginTest -->
